[workspace]
preview = ["pixi-build"]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["osx-arm64"]

[package]
name = "package_1"
version = "0.1.0"

[package.build.backend]
name = "pixi-build-python"
version = "*"

[package.build.source]
path = "package_1"

[package.build-dependencies]
python = "*"

[package.host-dependencies]
python = "*"
hatchling = "*"

[package.run-dependencies]
python = "*"
numpy = "*"

[dependencies]
package_1 = { path = "." }